# Generated by Django 5.1.5 on 2025-01-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesamientoArchivos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['concepto', '-uploaded_at']},
        ),
        migrations.AddField(
            model_name='invoice',
            name='concepto',
            field=models.CharField(default='Concepto no declarado por el usuario alalala', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='coste',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='formato',
            field=models.CharField(choices=[('number', 'Número'), ('currency', 'Moneda')], default='currency', max_length=10),
        ),
    ]
