# Generated by Django 5.1.5 on 2025-01-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesamientoArchivos', '0002_alter_invoice_options_invoice_concepto_invoice_coste_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='formato',
        ),
        migrations.AddField(
            model_name='invoice',
            name='tipo_factura',
            field=models.CharField(choices=[('cobrada', 'Cobrada'), ('pagada', 'Pagada')], default='pagada', max_length=10),
        ),
    ]
