# Generated by Django 5.1.5 on 2025-01-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesamientoArchivos', '0003_remove_invoice_formato_invoice_tipo_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro (€)'), ('USD', 'Dólar estadounidense ($)'), ('GBP', 'Libra esterlina (£)'), ('MXN', 'Peso mexicano (MXN)')], default='MXN', max_length=3),
        ),
    ]
