# Generated by Django 5.1.5 on 2025-01-28 11:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesamientoArchivos', '0004_invoice_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='concepto',
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['uploaded_at'], name='procesamien_uploade_967720_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['tipo_factura'], name='procesamien_tipo_fa_0bfcc2_idx'),
        ),
    ]
